from time import sleep
print(" Hình 1:")
print("      *")
print("      * *")
print("      * * *")
print("* * * * * * * *")
print("* * *")
print("* *")
print("*")
sleep(5)
print(" Hình 2:")
print("      *")
print("      * *")
print("      *   *")
print("* * * * * * * *")
print("*   *")
print("* *")
print("*")
sleep(5)
print(" Hình 3:")
print("      * * * *")
print("      * * *")
print("      * *")
print("      *")
print("    * *")
print("  * * *")
print("* * * * ")
sleep(5)
print(" Hình 4:")
print("      * * * *")
print("      *   *")
print("      * *")
print("      *")
print("    * *")
print("  *   *")
print("* * * * ")